package main

// generated by "schematyper CVE_JSON_4.0_min_public.schema" -- DO NOT EDIT

type affects struct {
	Vendor vendor `json:"vendor"`
}

type cveDataMeta struct {
	Assigner emailAddress `json:"ASSIGNER"`
	ID       cveID        `json:"ID"`
}

type cveID string

type cveJSON4 struct {
	Affects     affects     `json:"affects"`
	CveDataMeta cveDataMeta `json:"CVE_data_meta"`
	DataFormat  interface{} `json:"data_format"`
	DataType    interface{} `json:"data_type"`
	DataVersion interface{} `json:"data_version"`
	Description description `json:"description"`
	Problemtype problemtype `json:"problemtype"`
	References  references  `json:"references"`
}

type cveJson4Product struct {
	ProductName string  `json:"product_name"`
	Version     version `json:"version"`
}

type description struct {
	DescriptionData []langString `json:"description_data"`
}

type emailAddress string

type langString struct {
	Lang  string `json:"lang"`
	Value string `json:"value"`
}

type problemtype struct {
	ProblemtypeData []problemtypeDatum `json:"problemtype_data"`
}

type problemtypeDatum struct {
	Description []langString `json:"description"`
}

type reference struct {
	URL string `json:"url"`
}

type references struct {
	ReferenceData []reference `json:"reference_data"`
}

type vendor struct {
	VendorData []vendorDatum `json:"vendor_data"`
}

type vendorDatum struct {
	Product    vendorDatumProduct `json:"product"`
	VendorName string             `json:"vendor_name"`
}

type vendorDatumProduct struct {
	ProductData []cveJson4Product `json:"product_data"`
}

type version struct {
	VersionData []versionDatum `json:"version_data"`
}

type versionDatum struct {
	VersionValue string `json:"version_value"`
}
